import Head from "next/head";
import Image from "next/image";
import Main from "../components/Main";
import CssBaseline from "@material-ui/core/CssBaseline";
import "font-awesome/css/font-awesome.min.css";
import { config, library } from "@fortawesome/fontawesome-svg-core";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { fab } from "@fortawesome/free-brands-svg-icons";

config.autoAddCss = false;
library.add(fas, fab);

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />

                <script
                    src='https://kit.fontawesome.com/d9c25f1394.js'
                    crossOrigin='anonymous'
                    async></script>
            </Head>

            <main>
                <div className='body'>
                    <CssBaseline />

                    <Main />
                </div>
            </main>
        </div>
    );
}
